services:
  - type: web
    name: emotibot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vista.webapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
